# Generated by Django 4.2.3 on 2023-07-10 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='class_id',
            field=models.IntegerField(default=1, verbose_name='id класса'),
            preserve_default=False,
        ),
    ]
