# Generated by Django 4.2.3 on 2023-07-04 20:10

from django.db import migrations, models
import dogs.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('breed', '0002_alter_breed_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedigree_code', models.TextField(verbose_name='РКФ буквы')),
                ('pedigree_num', models.TextField(verbose_name='РКФ цифры')),
                ('region', models.TextField(verbose_name='Регион')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('is_male', models.BooleanField(verbose_name='Признак пола')),
                ('tattoo_code', models.TextField(verbose_name='Код клейма')),
                ('tattoo_num', models.TextField(verbose_name='Клеймо')),
                ('chip', models.TextField(verbose_name='Данные чипа')),
                ('name_ru', models.TextField(verbose_name='Кличка на русском')),
                ('name_en', models.TextField(verbose_name='Кличка на английском')),
                ('colour_ru', models.TextField(verbose_name='Окрас на русском')),
                ('colour_en', models.TextField(verbose_name='Окрас на английском')),
                ('breeder_id', models.IntegerField(verbose_name='Заводчик')),
                ('owner_id', models.IntegerField(verbose_name='Владелец')),
                ('father_id', models.IntegerField(verbose_name='Отец')),
                ('mother_id', models.IntegerField(verbose_name='Мама')),
                ('breed_id', models.ForeignKey(on_delete=models.SET(dogs.models.get_empty_breed_id), to='breed.breed')),
            ],
        ),
    ]
