# Generated by Django 4.2.3 on 2023-07-04 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='breed_id',
            field=models.IntegerField(verbose_name='id породы в таблице'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='chip',
            field=models.TextField(verbose_name='Чип'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='mother_id',
            field=models.IntegerField(verbose_name='Мать'),
        ),
    ]
