# Generated by Django 4.2 on 2023-07-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0002_alter_dog_breed_id_alter_dog_chip_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dog',
            options={'verbose_name': 'Собака', 'verbose_name_plural': 'Собаки'},
        ),
        migrations.RemoveField(
            model_name='dog',
            name='pedigree_code',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='pedigree_num',
        ),
        migrations.AddField(
            model_name='dog',
            name='rkf',
            field=models.TextField(default='', verbose_name='Номер РКФ'),
            preserve_default=False,
        ),
    ]
