# Generated by Django 4.2 on 2023-07-05 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0003_alter_dog_options_remove_dog_pedigree_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dog',
            old_name='tattoo_num',
            new_name='tattoo',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='tattoo_code',
        ),
    ]
