# Generated by Django 4.2.3 on 2023-07-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0004_rename_tattoo_num_dog_tattoo_remove_dog_tattoo_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='breeder_id',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='owner_id',
        ),
        migrations.AddField(
            model_name='dog',
            name='breeder',
            field=models.TextField(default='-', verbose_name='ФИО заводчика'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dog',
            name='owner',
            field=models.TextField(default='-', verbose_name='ФИО владельца'),
            preserve_default=False,
        ),
    ]
