# Generated by Django 4.2.3 on 2023-07-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0005_remove_dog_breeder_id_remove_dog_owner_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='father_id',
            field=models.TextField(verbose_name='Отец'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='mother_id',
            field=models.TextField(verbose_name='Мать'),
        ),
    ]
