# Generated by Django 4.2.3 on 2023-07-13 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0006_alter_dog_father_id_alter_dog_mother_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dog',
            old_name='father_id',
            new_name='father_tattoo',
        ),
    ]
