# Generated by Django 4.2.3 on 2023-07-13 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0007_rename_father_id_dog_father_tattoo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dog',
            old_name='mother_id',
            new_name='mother_tattoo',
        ),
    ]
