# Generated by Django 4.2.3 on 2023-10-26 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0008_rename_mother_id_dog_mother_tattoo'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='father_name',
            field=models.TextField(default='Кличка папы не указана', verbose_name='Кличка папы'),
            preserve_default=False,
        ),
    ]
