# Generated by Django 4.2.3 on 2023-10-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0010_dog_mother_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='short_address',
            field=models.TextField(default='Короткий адрес не указан', verbose_name='Короткий адрес'),
            preserve_default=False,
        ),
    ]
