# Generated by Django 4.2.3 on 2023-07-06 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.IntegerField(verbose_name='id Организатора')),
                ('name', models.TextField(verbose_name='Название события')),
                ('type', models.TextField(verbose_name='Название английское')),
                ('date', models.DateField(verbose_name='Дата проведения')),
                ('class_id', models.IntegerField(verbose_name='id Организатора')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
            },
        ),
    ]
