# Generated by Django 4.2.3 on 2023-07-10 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='class_id',
        ),
    ]
