# Generated by Django 4.2.3 on 2023-07-10 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_remove_event_class_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='name',
            new_name='comment',
        ),
    ]
