# Generated by Django 4.2.3 on 2023-07-10 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_rename_name_event_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='type',
        ),
        migrations.AddField(
            model_name='event',
            name='rank_id',
            field=models.IntegerField(default=1, verbose_name='id типа'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='type_id',
            field=models.IntegerField(default=1, verbose_name='id типа'),
            preserve_default=False,
        ),
    ]
