# Generated by Django 4.2.3 on 2023-07-03 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.IntegerField(verbose_name='Группа')),
                ('bid', models.IntegerField(verbose_name='Код породы')),
                ('name_ru', models.TextField(verbose_name='Название русское')),
                ('name_en', models.TextField(verbose_name='Название английское')),
                ('country_ru', models.TextField(verbose_name='Страна на русском')),
                ('country_en', models.TextField(verbose_name='Страна на английском')),
                ('size', models.TextField(verbose_name='Размер особи')),
            ],
        ),
    ]
