# Generated by Django 4.2.3 on 2023-07-04 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breed', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breed',
            options={'verbose_name': 'Порода', 'verbose_name_plural': 'Породы'},
        ),
    ]
